apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kdi-k8s.fullname" . }}
  labels:
    {{- include "kdi-k8s.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kdi-k8s.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kdi-k8s.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kdi-k8s.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: api-port
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          
          env:
            - name: KDI_K8S_API_PORT
              value: "{{ .Values.service.port }}"

            - name: KDI_WEB_API_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: {{ include "kdi-k8s.fullname" . }}
                  key: KDI_WEB_API_ENDPOINT
            
            - name: KDI_JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "kdi-k8s.fullname" . }}
                  key: KDI_JWT_SECRET_KEY
            
            - name: KDI_JWT_SUB_FOR_K8S_API
              valueFrom:
                secretKeyRef:
                  name: {{ include "kdi-k8s.fullname" . }}
                  key: KDI_JWT_SUB_FOR_K8S_API
            
            - name: KDI_HELM_DRIVER
              valueFrom:
                secretKeyRef:
                  name: {{ include "kdi-k8s.fullname" . }}
                  key: KDI_HELM_DRIVER