apiVersion: v1
kind: Service
metadata:
  name: {{ include "kdi-k8s.fullname" . }}
  labels: {{- include "kdi-k8s.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
  selector: {{- include "kdi-k8s.selectorLabels" . | nindent 4 }}
