name: CI Pipeline

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       shell: bash
  #       working-directory: ./kdi-k8s
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Set up Go
  #       uses: actions/setup-go@v4
  #       with:
  #         go-version: "1.22"

  #     - name: Build
  #       run: go build -v ./...

  #     - name: Test
  #       run: go test -v ./...

  build-docker-images:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3

        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # - name: Build and push Docker image for KDI-K8s
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: ./kdi-k8s
      #     push: true
      #     tags: ${{ secrets.DOCKER_USERNAME }}/kdi-k8s:latest
      #     cache-from: type=gha
      #     cache-to: type=gha,mode=max

      - name: Build and push Docker image for KDI-web
        uses: docker/build-push-action@v5
        with:
          context: ./kdi-web
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/kdi-web:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
 
      - name: Build and push Docker image for KDI-webapp
        uses: docker/build-push-action@v5
        with:
          context: ./kdi-webapp
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/kdi-webapp:latest
          secrets: |
            "kdi_web_api_endpoint=${{ secrets.KDI_WEBAPP_WEP_API_ENDPOINT }}"
            "kdi_web_msal_client_id=${{ secrets.KDI_WEBAPP_MSAL_CLIENT_ID }}"
            "kdi_web_msal_authority=${{ secrets.KDI_WEBAPP_MSAL_AUTHORITY }}"
            "kdi_web_msal_redirect_uri=${{ secrets.KDI_WEBAPP_MSAL_REDIRECT_URI }}"
            "kdi_web_msal_scope=${{ secrets.KDI_WEBAPP_MSAL_SCOPE }}"
          cache-from: type=gha
          cache-to: type=gha,mode=max
